name: CI/CD Pipeline 
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
 
    # - name: Install dependencies
    #   run: |
    #     npm install
 
    # - name: Build React app
    #   run: npm run build ada/ada-front
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@$31.207.35.107 << 'EOF'
          cd /www/project/ada
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF
